port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
redis:
  address: 127.0.0.1:6379
  password: DxQP5fyvNCeK19JodZu4A_PVRUnJiraA
keys:
  API57st43dmk: JJIEfuad1sOht_nYe7-L0sHVFQdCf3CMlSVxq1D9SDA
webhook:
  api_key: API57st43dmk
  urls:
    - https://video.openpbl.ai/api/webhooks/livekit
logging:
  level: info